const driverPoints = {
    "Max Verstappen": 166,
    "Sergio Perez": 75,
    "Charles Leclerc": 116,
    "Carlos Sainz": 83,
    "Lando Norris": 98,
    "Oscar Piastri": 68,
    "Lewis Hamilton": 40,
    "George Russell": 45,
    "Esteban OCON": 2,
    "Pierre Gasly": 3,
    "Fernando Alonso": 32,
    "Lance Stroll": 15,
    "Yuki Tsunoda": 17,
    "Daniel Ricciardo": 9,
    "Alexander Albon": 2,
    "Logan Sargeant": 0,
    "Kevin Magnussen": 1,
    "Nico Hulkenberg": 5,
    "Valtteri Bottas": 0,
    "GUANYU ZHOU": 0
  };