const driverPoints = {
    "Max Verstappen": 141,
    "Sergio Perez": 75,
    "Charles Leclerc": 116,
    "Carlos Sainz": 83,
    "Lando Norris": 80,
    "Oscar Piastri": 58,
    "Lewis Hamilton": 27,
    "George Russell": 37,
    "Esteban OCON": 1,
    "Pierre Gasly": 1,
    "Fernando Alonso": 24,
    "Lance Stroll": 9,
    "Yuki Tsunoda": 17,
    "Daniel Ricciardo": 5,
    "Alexander Albon": 2,
    "Logan Sargeant": 0,
    "Kevin Magnussen": 1,
    "Nico Hulkenberg": 5,
    "Valtteri Bottas": 0,
    "GUANYU ZHOU": 0
  };